In [456]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
set_info = pd.read_csv('/Users/kimjungwoo/Downloads/setter.csv')
set_info.head()

X = set_info.drop(['공격수','상대팀'],axis =1)
y = set_info[['공격수']]

print(set_info['공격수'][-30:])


print(y)





19939    디우프
19940    유서연
19941    고의정
19942    고의정
19943    유서연
19944    디우프
19945    디우프
19946    문지윤
19947    디우프
19948    문지윤
19949    디우프
19950    박혜민
19951    고민지
19952    문지윤
19953    고민지
19954    강소휘
19955    강소휘
19956    디우프
19957    박은진
19958    디우프
19959    고의정
19960    고의정
19961    유서연
19962    디우프
19963    고의정
19964    유서연
19965    나현수
19966    나현수
19967    문지윤
19968    고의정
Name: 공격수, dtype: object
       공격수
0       루소
1      이소영
2      양효진
3       러츠
4       러츠
...    ...
19964  유서연
19965  나현수
19966  나현수
19967  문지윤
19968  고의정

[19969 rows x 1 columns]


In [457]:
col_list = ["팀","세터","1번","2번","3번","4번","5번","6번"]

idx_list = []

for i in range(59):
    idx_list.append(i)

In [458]:
def encoder(box,name):
    le = LabelEncoder()
    le.fit(box[name])
    temp = le.transform(box[name])
    if(name=="공격수"):
        print(le.inverse_transform(idx_list))
    return temp

SyntaxError: invalid syntax (<ipython-input-458-c59b440e74d8>, line 6)

In [445]:

for i in col_list:
    print(i)
    X[i] = encoder(X,i)
#y = encoder(y,"공격수")
#print(X)
print(y[])


팀
세터
1번
2번
3번
4번
5번
6번
[21 38 33 20 20 21 33 20 21  0]


0        김다인
1        안혜진
2        김다인
3        안혜진
4        안혜진
        ... 
19964    안혜진
19965    하효림
19966    하효림
19967    이원정
19968    하효림
Name: 세터, Length: 19969, dtype: object


In [425]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = \
train_test_split(X, y, test_size = 0.2, random_state = 13)

In [426]:
import numpy as np

np.unique(y_train, return_counts = True)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
        35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
        52, 53, 54, 55, 56, 57, 58]),
 array([ 546,   88,  491,  202,   71,   11,    8,  241,   65,  226,  763,
         109,    1,  365,   51,  274,    9, 1391, 1114, 1143,  880,  154,
          31,  129,   70,    4,  167,  784,    1,   38,  289,  196,  545,
         225,  230,  128,   77,  624,   16,  721,  138,   43,  197,  163,
         568,    1,  100,    6,   13,  340,   21, 1023,  370,   18,  183,
          40,  239,   34]))

In [454]:
from sklearn.linear_model import LogisticRegression
from sklearn import svm
from sklearn.neighbors import KNeighborsClassifier

#clf = LogisticRegression()
#clf = svm.SVC(gamma = 0.001, C = 100)
clf = KNeighborsClassifier(n_neighbors=1)
clf.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=1)

In [455]:
from sklearn.metrics import accuracy_score

pred = clf.predict(X_train)
print(accuracy_score(y_train, pred))
print(pred[-30:])
print(y_train[-30:])


0.8005007824726135
[52 52 18 52 18 19 13  3 20 36 57 57 18 20 42 45 52  0 40 16 44 23 35 32
  2  0  2 57 20 18]
[52 52 18 52 18 19 13  3 20 36  2 57 18 38 42 45 52  0 14 16 52 23 19 32
  2  0  2 57 20 18]
